- hosts: publicly_routable
  sudo: yes
  tasks:
  - name: Install openshift-utils
    yum: name=atomic-openshift-utils state=present

  - name: Install exclude packages
    yum: name={{item}} state=present
    with_items:
    - atomic-openshift-excluder
    - atomic-openshift-docker-excluder
    - NetworkManager

  - name: Unexclude atomic during the installation
    shell: "atomic-openshift-excluder unexclude"

  - name: Copy inventory file to target
    copy: dest=/root/ src=../enterprise-inventory owner=root group=root mode=0600

  - name: "Cleanup hostfile"
    lineinfile:
       dest: /etc/hosts
       state: absent
       regexp: "^.*os3-.*$"

  - name: "Add private ips"
    lineinfile: 
      dest: /etc/hosts
      insertafter: EOF
      line:   "{{ hostvars[item].private_ipv4 }} {{ hostvars[item].ansible_hostname }}"
      state: present
    with_items: |
      {{ groups['all'] }}

  - name: "Add public ips"
    lineinfile:
      dest: /etc/hosts
      insertafter: EOF
      line:   "{{ hostvars[item].public_ipv4 }} {{hostvars[item].ansible_hostname}}.ose"
      state: present
    with_items: |
      {{ groups['all'] }}

  - name: create .ssh for root
    file: state=directory dest=/root/.ssh/ owner=root group=root mode=0700

  - name: add authorized keys file
    copy: dest=/root/.ssh/authorized_keys src=id_rsa.pub owner=root group=root mode=0600

  - name: add authorized keys file
    copy: dest=/root/.ssh/ src={{item}} owner=root group=root mode=0600
    with_items:
    - id_rsa
    - id_rsa.pub

